[[glog]]
arch = "aarch64"
git-tree-sha1 = "7e5c11f83dd4b60f08093f8f45cf408ae4bb19b9"
os = "macos"

    [[glog.download]]
    sha256 = "99ed2ff56ec397b4c51e72760a16320804784ad6c4f7af804274b9bb521367d6"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.aarch64-apple-darwin.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83671fb93e746369d94388f485a37145f6a5eabb"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "09eee5c905fc7ec8b910ba32d36c2a1b78aa40859e6130d433fc320a85d5abd6"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3be52476c7eb49a00de9beb8169c226e2f375866"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "0a3fd594eaf608cc2c576856970654888d0b8d74bcc39e50e7bd4d0da64f3992"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82c2eefed87523cfef042cd56da966a624ff644e"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "a5a1875b4dd0d8849aa2e6c3d059f34e3cab1fd6882ab2d6de2aa1c5e98cfbff"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d2d2813dd6e2910287be74dfbf2a4a25d233d94"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "2a9aea3b176cfd52421be5ddf8c61492c30b54bf1cbfa4be5b883fa92a0fedf5"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38401c647b2622c22a02dfe4475c869981865800"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "3bc19524dc2419099bed5bc0fb275cd8113321d8bf8382ee2c52a6f16cae41de"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[glog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac2dad74e931d5fd1b01239306ad5acff494e282"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "8cd1abe8b75b7c3644e3bffe201610c4f24027bbeeedb9c009ae38f6cef90b45"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[glog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26896ed4f71870768f84e4adbfe157c36b804c00"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "29aebbcbb91fc72bc2f2ef29438cc7fd77ef76a08c166c4a84f919464034483c"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[glog]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7936c3423d6b7f0faa2f4fbd578652da9b368c37"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "ff8e636b822f46cc631dff878c0741807dfbe47257bb5f93d77143419408b2e0"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[glog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c9ede3e45e04993b9f255bd13790d70321d7fbf"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "3744a7e6f47209c9a5d9bf69a19b0bcbc3b80d1e086f64b32e98d7c38e2e6cfa"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[glog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "383acfa298b6e76001237a9e3f3c3be9d2edf1c0"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "405744d7adea85fd47204f0b13c7e5f5d328dbdcb2c36bdc5085c1cc03944109"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[glog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3340bf6250b8f1c4ec596b742c133ef7663fce81"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "c7ba0c2cac198b46f609d8c83c8f24a9a80a9d540d4a84fca74d752c648e0c30"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[glog]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df6054a41a3cdbb49518ad024d84c2bb082021c7"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "9c3945a5e3bbb5b5dd10ca2061eb281625b51baf292bd4aa471cbc8f4fd14b21"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a65eb463b47b6b4bc23f1bf5ca18c1812690aff"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "eb4f443dce65e01fa8e961292f8154be58e9d27ba6942251fe67ccfc5f0f37c4"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ad4e6990f08212f0a54b319f226bd31ec822d93"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "22086340beabf6448fcc9de05dcdef620b6a88367d651eb14a798742eddc4ee4"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "532471e588b8d7ce374fbf06734e01b9648e2f25"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "0b8c1adba8690f7b6ea02c50ad9968d5587d3ad04a8c7ec190c7b7bfaf3a564d"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-linux-musl-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0be93c4314e1b8e0ee09328043c2f60dc8276a8"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "eab5437ec592e4075129c687f198b7f5b38a77bb10ddc251c17075671654342e"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19ebca688048f84ec07fb08b1bc96ba4bab1a27b"
os = "windows"

    [[glog.download]]
    sha256 = "40d07d2a4cbcc7531c72ef27bd1552df2d4c62f518064745ade23b510c3eca9e"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ac9fe0858ceaa2bf56c992bf1771995275266ac"
os = "windows"

    [[glog.download]]
    sha256 = "bc32d47655b10fd23bd65b88ea2d8b4056fd9067a6d50cad1f3f916dbcdd0566"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[glog]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c12785d56e93c3289e8320d168e1ac2a90532fd"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "a9bcf323364ac33263359ffe496f5fe60d75e0f78dc0986ca5c197c3cf563b00"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb8ea64fa42e117af93c960ddf84fc0a501a1e53"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "d5ce61266704dcf66f28d783a94946796387c5d952129ea53386bb1feaed9002"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
git-tree-sha1 = "bd704406fde9baaf40bca396d9f31c7dd1cb76ce"
os = "macos"

    [[glog.download]]
    sha256 = "edf173dea761c87dc8e52b31e21cc7ae35212d888b95fa543ea475e5351b7545"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-apple-darwin.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "801455c5d4fe50e614ac91c2705c7802eb46740a"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "5c9b1a62936645b1173c1715af3d0e8dea806daaee1e63c8e1911ed0e083912e"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee1f67e175c734ed5010857dd89b652aa369ee9b"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "d481f0f4b7a9e7fceff2a4d9b924fcad83afd2a34e368d9b7d60add35d0da539"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9a374953d965714d767255653a761bbbdbd858f"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "c4fcf7ea00b86c18c59ff700379c925c131a122fb843fd496dc7ecec60c82a5f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b422e281d630f4396f7a45f8d50027c2eba07333"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "da9280111141c5b7eaf1d38422531824e7f90e8438e3db88bb592f2127dddcfc"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
git-tree-sha1 = "2c14f542e00f461ca25d1016293daec94dca04ff"
os = "freebsd"

    [[glog.download]]
    sha256 = "4e06805a40c8f0a99a229518434c11d62cb679b4aa903fb502b1e148a7a5bd66"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-unknown-freebsd.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71d3a8ce37a3e829b1f0827d7aaa6ea219f793f6"
os = "windows"

    [[glog.download]]
    sha256 = "650a819adf73ab35a71bfd34b6005de035ec496ef1897fb921acfee753c6ee4c"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "816220e9d6796c84431b4a9ad5763e1568e5f500"
os = "windows"

    [[glog.download]]
    sha256 = "0c55555c4359a88f842fd9fd55d5e212f1c7150fea70e3f3504d375ef6f1f19c"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.6.0+0/glog.v0.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
