[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8a64d0c383e4e0580ad82a896efc21953ac83a5"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "af7cb95354f85a457cdd146f019effd4aec959edad286c734d849b34d791c63e"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdcaff89489f4b92ea0d2a7d60c5e80fb57639c7"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "686901cf17af94d2e79413778431e4229dd9f555df58a97bd4416c230c278838"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1f77ac888b5e26d3c20b13342be31b0faf7378a"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "8d986516bcf113627aaf9e107df19ed9f2d5437f50865c53a6907052b339fc34"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb2eed41c822da6d6e40c601d822aa378ec823fd"
os = "windows"

    [[glog.download]]
    sha256 = "64cd9377ff62d67199a1adcb5fcecdeeeb52deba0aa0b0318111b97b5a001b7f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dea3e5c879caff9bb56f4dd6bee89f41b489863"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "59e82095826662278ef19089d2964efdd57e4c198ca5a6aa2ee9d76795c81e6f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6da2fda9785c5c3ed406643a33d5e53251ab874"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "c5429d2999b15f97a06a6d0f67144543b784124caa7b502083c6c4687224f0e5"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b64a0f95578c3521f033dbd5f1efa8a9ac08f8c3"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "24554598850068ff170f54f85d7d452bc14ee5c19939258aad777c8b4c549363"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "364ca92922e8e103d499f0ef91ef27c0a23c4213"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "b1c76898ed9d10d89cf03de194250d4056b56455cba65ca774a6f752912ffa46"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1309c8bd8fd3e87895e9b6a0eed560d49d65ec2b"
os = "macos"

    [[glog.download]]
    sha256 = "1141d689328ae56ae806c721d2407a97a8ce2f5332a0ba3cb12f53cb88eb1c56"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc75f6e178bad50381b7ad0445add691ffb4cd2b"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "3edb138f261e8cccfb8e099292a21cfd3b50861054589c293eaeb0595e5bf061"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "889641fc99e844859a70302a3f8a163e8e6ef3f0"
os = "windows"

    [[glog.download]]
    sha256 = "ebbe41a19e37f229a152d5ca96e987acba66a126b33c50245cad4227cc976261"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e970e6215c360be9dba5f851202b57ed5c4507f"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "c86bb21c237155422661013ee59af60055da4c43c511fce30115b7bfe69536c7"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6db43587fb191f2260b5fce4c389486c73ad3909"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "9ea831d0c89a04049b562311d0c6dbeda521b688e0e72aaadc8ced58cbae3662"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd7c05fc089f7202df1eb555326239c67c3961bb"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "ec6a07496ccefd3e5a6d75e7d410c8965794dc99b7c72349a4f24052aaa26115"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34cfc6ced958f99bf020d3778ae2ba7175046000"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "168083ab5fba7a1aea7501ad75d99dce9a0d0702b1105de86512752b587dc2f3"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aadfc2904583e03068761e143ab7596cddd50e2"
os = "macos"

    [[glog.download]]
    sha256 = "d8ca8c5f4cf119ef8b2e7bef398fa0cc272e3c9e2423cbfc2cf678caad7a0832"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c360fd97db0bb73c56b17e535506746c7accb8b"
os = "freebsd"

    [[glog.download]]
    sha256 = "f64064268c5b3daed6a7a6aa92ba898d284ae2ee7d8cc41c40a7106ecb64fd5f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[glog]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798647e4a6344a6d9fddaec0e7ce50800d6af1c6"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "7c515ed88a4eb2dcf5398023749939255b0e7a859dea79d41fccf48de78518be"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ffd216d22c7b7ca4baee43168b40eddd44d5169"
os = "windows"

    [[glog.download]]
    sha256 = "20ca48b7b75392375c358e881147a323f15cee0f9d2583a5a4659c2157c820d7"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0ae47e4d06b3f85372e3f53a8354c06208cd384"
os = "windows"

    [[glog.download]]
    sha256 = "bf9ec37971d598a2c5aa215ede101b610efc560874421690f7b6c68d87ce846f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[glog]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7ccf03fa8f469499507b07f1211125defdece92"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "43040dca942e3b1fc04e9277511749da856e22521e137708d9bc51fb418eec91"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[glog]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb12f68ca1276b3c32e4d56feb0ccbaeab136176"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "74fc9252f84f62b5f8482fe08f6b8ff41b787f4683fa5aa8629e83fba3824fa3"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[glog]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c0976a95d86fe2fe51313e70ba4680c0b3e8871"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "8f7885c1146bf3565b2720dabc9033b2827189956cad670c36731648f8c63339"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[glog]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbafae4f30f79e9605e0ad783b0a63fabb1b732a"
libc = "glibc"
os = "linux"

    [[glog.download]]
    sha256 = "1777e0c6a5596244ff60f39d5781e3245c9f9cbf90136bd69646c9fc88373bb6"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[glog]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a94b8355b881c4be95e8ac4f10ceab3b2880d70"
os = "freebsd"

    [[glog.download]]
    sha256 = "0b79236e3215c7892aa1e65609a6bd0aabc5e6146a1cfea741341ff3dd438fa0"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[glog]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e65baff6f57af05fabb2f75b11b935e34f556d66"
libc = "musl"
os = "linux"

    [[glog.download]]
    sha256 = "014ddf68693b21ceeed509fea92d1699207aa27be3fae0e2fda6399fbd223a1f"
    url = "https://github.com/JuliaBinaryWrappers/glog_jll.jl/releases/download/glog-v0.4.0+0/glog.v0.4.0.i686-linux-musl-cxx03.tar.gz"
