# Autogenerated wrapper script for glog_jll for aarch64-apple-darwin
export libglog

using gflags_jll
JLLWrappers.@generate_wrapper_header("glog")
JLLWrappers.@declare_library_product(libglog, "@rpath/libglog.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(gflags_jll)
    JLLWrappers.@init_library_product(
        libglog,
        "lib/libglog.0.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
