# Autogenerated wrapper script for glog_jll for x86_64-w64-mingw32-cxx11
export libglog

using gflags_jll
JLLWrappers.@generate_wrapper_header("glog")
JLLWrappers.@declare_library_product(libglog, "libglog.dll")
function __init__()
    JLLWrappers.@generate_init_header(gflags_jll)
    JLLWrappers.@init_library_product(
        libglog,
        "bin\\libglog.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
